<a href="https://colab.research.google.com/github/sohel305/AIML/blob/main/2nd_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)
np

1.26.4


<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
A2=np.array([[1,2,3,4],[5,6,7,8]])
print(A2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
type(A2)

numpy.ndarray

In [ ]:
A2.shape

(2, 4)

In [ ]:
A2.shape

(2, 4)

In [ ]:
A2.size

8

In [ ]:
A2.ndim

2

In [ ]:
A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
type(A3)

numpy.ndarray

In [ ]:
A3.shape

(1, 3, 3)

In [ ]:
A3.size

9

In [ ]:
A3.ndim

3

In [ ]:
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [ ]:
z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [ ]:
type(z1)

numpy.ndarray

In [ ]:
z1.shape

(3,)

In [ ]:
z1.size

3

In [ ]:
z1.ndim

1

In [ ]:
z2=np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
z2=np.zeros((3,4),dtype=int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
type(z2)

numpy.ndarray

In [ ]:
z2.shape

(3, 4)

In [ ]:
z2.size

12

In [ ]:
z2.ndim

2

In [ ]:
z3=np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
z3=np.zeros((2,3,4),dtype=int)
z3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
type(z3)

numpy.ndarray

In [ ]:
z3.shape

(2, 3, 4)

In [ ]:
z3.size

24

In [ ]:
z3.ndim

3